### ISSUE TITLE
Show how to do deferred code loading transparently with ReactLoadable

### ISSUE THREAD

**Issue by deanrad** [William-Woodhead/simple-universal-react-redux#4]
While SSR tends to address the data-loading issue, many apps are plagued by high initial load times:

Would including `react-loadable` in this project be of interest to you?
https://github.com/jamiebuilds/react-loadable#happy-customers

**Comment by nofable** [comment]
This is a really interesting point. I'm really interested in dynamic code-splitting but I think for the purposes of this repo, I wanted to keep things as simple as possible. Thanks though!
